import type { TabId } from "./tabs";

export const widgetDefaults = {
  visibility: {
    "controls.motion": true,
    "controls.maxVelocity": true,
    "controls.gripper": true,
    "live.dashboard": true,
    "live.rviz": true,
    "articular.joints": true,
    "articular.gripper": true,
    "articular.rviz": true,
    "articular.jointGraphs": true,
    "camera.feed": true,
    "camera.settings": true,
    "camera.actions": true,
    "poses.saved": true,
    "poses.builder": true,
    "poses.preview": true,
    "petanque.status": true,
    "petanque.actions": true,
    "petanque.vision": true,
    "servo.controls": true,
    "servo.visuals": true,
    "curves.plots": true,
    "logs.recording": true,
    "logs.session": true,
    "config.appearance": true,
    "config.advanced": true,
    "config.axis": true,
    "debug.summary": true,
    "debug.streams": true,
  },
  titles: {
    "controls.motion": "Motion Controls",
    "controls.maxVelocity": "Max Velocity",
    "controls.gripper": "Gripper Control",
    "live.dashboard": "Live Teleoperation Dashboard",
    "live.rviz": "RViz Live",
    "articular.joints": "Articular Control",
    "articular.gripper": "Gripper",
    "articular.rviz": "RViz Live",
    "articular.jointGraphs": "Joint Graphs",
    "camera.feed": "Camera",
    "camera.settings": "Camera Settings",
    "camera.actions": "Actions",
    "poses.saved": "Saved Poses",
    "poses.builder": "Trajectory Builder",
    "poses.preview": "Trajectory Preview",
    "petanque.status": "Pétanque Mode",
    "petanque.actions": "Robot Actions",
    "petanque.vision": "Vision & Trajectory",
    "servo.controls": "Visual Servoing",
    "servo.visuals": "Live View",
    "curves.plots": "Courbes",
    "logs.recording": "Recording",
    "logs.session": "Active Session",
    "config.appearance": "Appearance",
    "config.advanced": "Advanced Configuration",
    "config.axis": "Axis Inversion",
    "debug.summary": "Debug",
    "debug.streams": "Low-level Streams",
  },
} as const;

export type WidgetId = keyof typeof widgetDefaults.visibility;

export const widgetsByTab: Record<TabId, WidgetId[]> = {
  controls: ["controls.motion", "controls.maxVelocity", "controls.gripper"],
  live_teleop: ["live.dashboard", "live.rviz"],
  articular: ["articular.joints", "articular.gripper", "articular.rviz", "articular.jointGraphs"],
  camera: ["camera.feed", "camera.settings", "camera.actions"],
  poses: ["poses.saved", "poses.builder", "poses.preview"],
  petanque: ["petanque.status", "petanque.actions", "petanque.vision"],
  visual_servoing: ["servo.controls", "servo.visuals"],
  curves: ["curves.plots"],
  logs: ["logs.recording", "logs.session"],
  configurations: ["config.appearance", "config.advanced", "config.axis"],
  debug: ["debug.summary", "debug.streams"],
};
